repos:
  - repo: local
    hooks:
      - id: ormolu
        name: ormolu format
        entry: ormolu -i
        language: system
        types: [haskell]
        pass_filenames: true
  - repo: local
    hooks:
      - id: stack_test
        name: stack test
        entry: stack test
        language: system
        types: []
        always_run: true
        pass_filenames: false
